name: Crowdin Action

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.2.0
      with:
        upload_translations: true

        download_translations: true
        push_translations: true
        commit_message: 'New Crowdin translationby Github Action'

        localization_branch_name: l10n_crowdin_action
        create_pull_request: true
        pull_request_title: 'New Crowdin translations'

        crowdin_branch_name: l10n_branch
        config: './web/crowdin.yml'

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: '463460'
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}