project_id: '463460'
api_token: '{{ secrets.CROWDIN_PERSONAL_TOKEN }}'
preserve_hierarchy: true
files: [
    # JSON translation files
    {
      source: '/src/locales/en/**/*',
      translation: '/src/locales/%two_letters_code%/**/%original_file_name%',
    },
  ]
